### ISSUE TITLE
[MI-011] Replace Removed Hibernate 5 Query and Session APIs

### ISSUE THREAD

**Issue by Willchrist** [UST-PACE/ticket-booking#251]
## What needs to change

Hibernate 6 (bundled with Spring Boot 3.x) removed several legacy query and session APIs that were available in Hibernate 5. Specifically, `Query.list()`, `Query.uniqueResult()`, and `Session.load()` no longer exist and must be replaced with their JPA-standard or Hibernate 6 equivalents. Every call site across the persistence layer must be updated to use `getResultList()`, `getSingleResultOrNull()`, and `session.get()` respectively.

## Why this matters

Leaving these calls in place causes compile-time failures immediately after upgrading the Spring Boot parent BOM to 3.4.x, because the methods no longer exist on the Hibernate 6 API surface. Any call site that is missed will throw `NoSuchMethodError` at runtime, resulting in broken data-access operations.

## Files to change

- `src/main/java` — all source files that invoke `.list()`, `.uniqueResult()`, or `.load(` on Hibernate `Query` or `Session` objects.

  Run the following command to locate every affected file before starting:
  ```
  grep -rn "\.list()\|\.uniqueResult()\|\.load(" src/
  ```

## Implementation steps

1. Run the grep command above to produce a complete list of every affected call site and note each file and line number.
2. For every occurrence of `query.list()`, replace it with `query.getResultList()`.
3. For every occurrence of `query.uniqueResult()`, replace it with `query.getSingleResultOrNull()`. Remove any explicit `(YourEntity)` cast if the `Query` is already typed (i.e., `Query<YourEntity>`); keep the cast only if a raw `Query` type is unavoidable.
4. For every occurrence of `session.load(SomeClass.class, id)`, replace it with `session.get(SomeClass.class, id)`. Note the semantic difference: `session.load()` previously returned a proxy and threw `ObjectNotFoundException` on access if the entity did not exist, whereas `session.get()` returns `null` immediately — verify that callers handle a possible `null` return value.
5. Ensure that any surrounding `null` checks or `Optional` wrapping are adjusted where `session.load()` was previously relied upon to never return `null`.
6. Compile the full project (`./mvnw clean compile` or `./gradlew compileJava`) and confirm zero errors.
7. Run all existing persistence-layer and integration tests to verify no behavioural regressions.

## Code changes

Replace the three removed Hibernate 5 APIs with their Hibernate 6 equivalents at every call site identified by the grep search.

**Before:**
```java
// Removed Hibernate 5 APIs:
List<Order> orders = query.list();
Order order = (Order) query.uniqueResult();
Order order = session.load(Order.class, id);
```

**After:**
```java
// Hibernate 6 replacements:
List<Order> orders = query.getResultList();
Order order = query.getSingleResultOrNull();
Order order = session.get(Order.class, id);

// Find usages: grep -rn "\.list()\|\.uniqueResult()\|\.load(" src/
```

## Acceptance criteria

- [ ] `grep -rn "\.list()\|\.uniqueResult()\|\.load(" src/` returns zero matches across all production source files.
- [ ] All `query.list()` call sites have been replaced with `query.getResultList()`.
- [ ] All `query.uniqueResult()` call sites have been replaced with `query.getSingleResultOrNull()`, with casts removed where the `Query` is already typed.
- [ ] All `session.load()` call sites have been replaced with `session.get()`, and callers correctly handle a `null` return value.
- [ ] `./mvnw clean compile` (or `./gradlew compileJava`) completes with zero compilation errors.
- [ ] All existing unit and integration tests for the persistence layer pass without modification to test assertions.
- [ ] No new `NullPointerException` or `ObjectNotFoundException` regressions are introduced at previously safe `session.load()` call sites.

## Depends on

- Upgrade Spring Boot Parent BOM to 3.4.x

---
*PACE Migration Tool — MI-011 | Priority: HIGH | Effort: 2.0h*
